// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIGvi55Pv6mAMoPlAO1kbfI8dxuhJtWh4',
    appId: '1:1068238252185:web:cb25269dc8a505ad917008',
    messagingSenderId: '1068238252185',
    projectId: 'calmi-21168',
    authDomain: 'calmi-21168.firebaseapp.com',
    storageBucket: 'calmi-21168.firebasestorage.app',
    measurementId: 'G-DNC5BJT12T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZTsoSlhW8FZl5BO-WeaNDwK-ZVqZmgYo',
    appId: '1:1068238252185:android:a03879ea31566662917008',
    messagingSenderId: '1068238252185',
    projectId: 'calmi-21168',
    storageBucket: 'calmi-21168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbCzGMx7w6sFZ3-c31uXPgSxq7Iv9m0dY',
    appId: '1:1068238252185:ios:48de4d92ab1c7a4a917008',
    messagingSenderId: '1068238252185',
    projectId: 'calmi-21168',
    storageBucket: 'calmi-21168.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIGvi55Pv6mAMoPlAO1kbfI8dxuhJtWh4',
    appId: '1:1068238252185:web:659d6eed16798a40917008',
    messagingSenderId: '1068238252185',
    projectId: 'calmi-21168',
    authDomain: 'calmi-21168.firebaseapp.com',
    storageBucket: 'calmi-21168.firebasestorage.app',
    measurementId: 'G-EL39HCZTTY',
  );

}